"""
ASCII Art MCP Server

Four tools:
  ascii_generate     → text prompt → OpenRouter image → PIL → ASCII string
  ascii_refine       → existing art + feedback → improved ASCII string (LLM)
  ascii_convert      → local image path → ASCII string (PIL only, no API)
  ascii_list_styles  → returns available style presets

Requires: OPENROUTER_API_KEY in environment for ascii_generate.
See ASCII_ART_MCP_LOG.md in lms_mcp/ for full architecture notes.
"""

import os
import sys
from pathlib import Path

from mcp.server.fastmcp import FastMCP

# Load OPENROUTER_API_KEY from a local .env if present (path-agnostic:
# checks the server dir, then the vendored package dir)
_env_file = Path(__file__).parent / ".env"
if not _env_file.exists():
    _env_file = Path(__file__).parent / "ascii_art" / ".env"
if _env_file.exists():
    for _line in _env_file.read_text().splitlines():
        _line = _line.strip()
        if _line and not _line.startswith("#") and "=" in _line:
            _k, _, _v = _line.partition("=")
            os.environ.setdefault(_k.strip(), _v.strip())

mcp = FastMCP("ascii_art_mcp")


# ── Tool 1: generate ──────────────────────────────────────────────────────────

@mcp.tool(
    name="ascii_generate",
    annotations={
        "readOnlyHint": False,
        "destructiveHint": False,
        "idempotentHint": False,
        "openWorldHint": True,
    },
)
def ascii_generate(
    subject: str,
    width: int = 80,
    style: str = "detailed",
) -> str:
    """
    Generate ASCII art from a text description.

    **PIPELINE:** text prompt → OpenRouter (gemini-2.5-flash-image) → real image →
    PIL brightness mapping → ASCII string. No LLM spatial guessing — pixel-accurate.

    **TRIGGER:** Use whenever you need ASCII art of any subject. This is the primary tool.

    **Args:**
      subject: What to draw. Be specific — "a sitting tabby cat" beats "a cat".
               For best results, add visual context: pose, angle, style notes.
      width:   Output width in characters (default 80). Common values: 40, 60, 80, 120.
      style:   Visual treatment. Run ascii_list_styles to see options.
               Most useful values: "detailed" (default), "minimal", "dense", "outline".

    **Cost:** ~$0.04 per call (Imagen 3 flat rate via OpenRouter).

    **Returns:** Plain ASCII string, newline-separated rows, no markdown fences.
    Each row is padded to exactly `width` characters.

    **Example subjects that work well:**
      "a human skull, frontal view"
      "a sitting cat, side profile"
      "a rocket launching, view from below"
      "a dragon breathing fire, fantasy illustration"
    """
    from ascii_art.image_pipeline import ImagePipeline

    pipeline = ImagePipeline()
    return pipeline.generate(subject, width=width, style=style)


# ── Tool 2: refine ────────────────────────────────────────────────────────────

@mcp.tool(
    name="ascii_refine",
    annotations={
        "readOnlyHint": False,
        "destructiveHint": False,
        "idempotentHint": False,
        "openWorldHint": True,
    },
)
def ascii_refine(
    art: str,
    feedback: str,
    width: int = 80,
) -> str:
    """
    Improve existing ASCII art based on explicit feedback.

    **PIPELINE:** art string + feedback → local Ollama LLM (ascii-artist model) → revised art.
    Use this to apply targeted corrections to art generated by ascii_generate.

    **TRIGGER:** Use after ascii_generate when the result needs specific adjustments.
    Describe exactly what is wrong — spatial issues, proportions, missing features.

    **CONSTRAINT:** Requires Ollama running locally with the ascii-artist model loaded.
    Quality is lower than ascii_generate; for large structural changes, regenerate instead.

    **Args:**
      art:      The ASCII art string to improve (output of ascii_generate or ascii_convert).
      feedback: Specific critique. Good: "the ears are too small and the tail is missing".
                Bad: "make it better". Be spatial and concrete.
      width:    Output width in characters (should match original art width).

    **Returns:** Revised ASCII art string, same format as ascii_generate output.

    **Tip:** If refine produces worse results, discard and call ascii_generate again
    with a more descriptive subject string instead.
    """
    from ascii_art.generator import ASCIIArtGenerator

    gen = ASCIIArtGenerator()
    return gen.refine(art.strip(), feedback, width=width, stream=False)


# ── Tool 3: convert ───────────────────────────────────────────────────────────

@mcp.tool(
    name="ascii_convert",
    annotations={
        "readOnlyHint": True,
        "destructiveHint": False,
        "idempotentHint": True,
        "openWorldHint": False,
    },
)
def ascii_convert(
    image_path: str,
    width: int = 80,
) -> str:
    """
    Convert a local image file to ASCII art using PIL brightness mapping.

    **PIPELINE:** local file → PIL grayscale → brightness ramp → ASCII string.
    No API call, no cost, instant. Works on any image format PIL supports
    (PNG, JPEG, BMP, WEBP, GIF first frame, etc.).

    **TRIGGER:** Use when you already have an image file on disk and want ASCII art from it.
    Also useful for previewing or repurposing existing screenshots or photos.

    **CONSTRAINT:** Image must be a local path accessible to the server process.
    For dark-background images the ramp is auto-inverted so the subject is dense chars.

    **Args:**
      image_path: Absolute path to the image file.
      width:      Output width in characters (default 80).

    **Returns:** ASCII art string, same format as ascii_generate.

    **Aspect ratio note:** Output height is computed as width × image_aspect × 0.45
    to compensate for terminal characters being ~2× taller than wide.
    """
    from ascii_art.image_pipeline import image_to_ascii

    path = Path(image_path)
    if not path.exists():
        return f"Error: file not found: {image_path}"
    if not path.is_file():
        return f"Error: not a file: {image_path}"

    with open(path, "rb") as f:
        return image_to_ascii(f.read(), width=width)


# ── Tool 4: list_styles ───────────────────────────────────────────────────────

@mcp.tool(
    name="ascii_list_styles",
    annotations={
        "readOnlyHint": True,
        "destructiveHint": False,
        "idempotentHint": True,
        "openWorldHint": False,
    },
)
def ascii_list_styles() -> str:
    """
    List available style presets for ascii_generate and ascii_refine.

    **TRIGGER:** Call before ascii_generate when the user mentions a visual treatment
    (e.g. "minimal", "sketchy", "bold") and you want to confirm the exact style name.

    **Returns:** Newline-separated list of style names and their descriptions.
    Pass the style name (left column) to ascii_generate's `style` parameter.
    """
    from ascii_art.config import STYLES

    return "\n".join(f"{name:10s} — {desc}" for name, desc in STYLES.items())


# ── Entrypoint ────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    mcp.run()
